const NS_PUBLISH_STORE = "publishStore";

const SET_LOADING_STEP = `${NS_PUBLISH_STORE}/setGlobalLoading`;
const GET_ALL_PUBLISHS = `${NS_PUBLISH_STORE}/getAllPublishs`;
const SAVE_ALL_PUBLISHS = `${NS_PUBLISH_STORE}/saveAllPublishs`;
const CREATE_PUBLISH_REQUEST = `${NS_PUBLISH_STORE}/createPublishRequest`;
const UPDATE_PUBLISH_REQUEST = `${NS_PUBLISH_STORE}/updatePublishRequest`;
const SAVE_UPDATE_PUBLISH = `${NS_PUBLISH_STORE}/saveUpdateRequest`;
const GET_DETAIL_PUBLISH = `${NS_PUBLISH_STORE}/getDetailPublish`;
const SAVE_DETAIL_PUBLISH = `${NS_PUBLISH_STORE}/saveDetailPublish`;
const DELETE_PUBLISH_REQUEST = `${NS_PUBLISH_STORE}/deletePublishRequest`;

export {
  NS_PUBLISH_STORE,
  SET_LOADING_STEP,
  GET_ALL_PUBLISHS,
  SAVE_ALL_PUBLISHS,
  CREATE_PUBLISH_REQUEST,
  UPDATE_PUBLISH_REQUEST,
  SAVE_UPDATE_PUBLISH,
  GET_DETAIL_PUBLISH,
  SAVE_DETAIL_PUBLISH,
  DELETE_PUBLISH_REQUEST,
};
