const NS_BOOK_STORE = "bookStore";

const SET_LOADING_STEP = `${NS_BOOK_STORE}/setGlobalLoading`;

const NS_DANG3_STORE = "dang3Store";

const GET_ALL_DANG3 = `${NS_DANG3_STORE}/getAllDang3`;
const SAVE_ALL_DANG3 = `${NS_DANG3_STORE}/saveAllDang3`;
const GET_DETAIL_DANG3 = `${NS_DANG3_STORE}/getDetailDang3`;
const SAVE_DETAIL_DANG3 = `${NS_DANG3_STORE}/saveDetailDang3`;
const UPDATE_DANG3_REQUEST = `${NS_DANG3_STORE}/updateDang3Request`;
const SAVE_UPDATE_DANG3 = `${NS_DANG3_STORE}/saveUpdateDang3`;
const CREATE_DANG3_REQUEST = `${NS_DANG3_STORE}/createDang3Request`;
const DELETE_DANG3_REQUEST = `${NS_DANG3_STORE}/deleteDang3Request`;
export {
  NS_BOOK_STORE,
  SET_LOADING_STEP,
  GET_ALL_DANG3,
  SAVE_ALL_DANG3,
  GET_DETAIL_DANG3,
  SAVE_DETAIL_DANG3,
  UPDATE_DANG3_REQUEST,
  SAVE_UPDATE_DANG3,
  CREATE_DANG3_REQUEST,
  DELETE_DANG3_REQUEST,
};
