const NS_BOOK_STORE = "bookStore";

const SET_LOADING_STEP = `${NS_BOOK_STORE}/setGlobalLoading`;

const NS_ADMINMULMEDIA_STORE = "adminmulmediaStore";

const GET_ALL_ADMINMULMEDIA = `${NS_ADMINMULMEDIA_STORE}/getAllAdminMulmedia`;
const SAVE_ALL_ADMINMULMEDIA = `${NS_ADMINMULMEDIA_STORE}/saveAllAdminMulmedia`;
const GET_DETAIL_ADMINMULMEDIA = `${NS_ADMINMULMEDIA_STORE}/getDetailAdminMulmedia`;
const SAVE_DETAIL_ADMINMULMEDIA = `${NS_ADMINMULMEDIA_STORE}/saveDetailAdminMulmedia`;
const UPDATE_ADMINMULMEDIA_REQUEST = `${NS_ADMINMULMEDIA_STORE}/updateAdminMulmediaRequest`;
const SAVE_UPDATE_ADMINMULMEDIA = `${NS_ADMINMULMEDIA_STORE}/saveUpdateAdminMulmedia`;
const CREATE_ADMINMULMEDIA_REQUEST = `${NS_ADMINMULMEDIA_STORE}/createAdminMulmediaRequest`;
const DELETE_ADMINMULMEDIA_REQUEST = `${NS_ADMINMULMEDIA_STORE}/deleteAdminMulmediaRequest`;
export {
  NS_BOOK_STORE,
  SET_LOADING_STEP,
  GET_ALL_ADMINMULMEDIA,
  SAVE_ALL_ADMINMULMEDIA,
  GET_DETAIL_ADMINMULMEDIA,
  SAVE_DETAIL_ADMINMULMEDIA,
  UPDATE_ADMINMULMEDIA_REQUEST,
  SAVE_UPDATE_ADMINMULMEDIA,
  CREATE_ADMINMULMEDIA_REQUEST,
  DELETE_ADMINMULMEDIA_REQUEST,
};
