const NS_BOOK_STORE = "bookStore";

const NS_ADMINBOOKNEW_STORE = "adminbooknewStore";
const SET_LOADING_STEP = `${NS_BOOK_STORE}/setGlobalLoading`;

const GET_ALL_ADMINBOOKNEW = `${NS_ADMINBOOKNEW_STORE}/getAllAdminBookNew`;
const SAVE_ALL_ADMINBOOKNEW = `${NS_ADMINBOOKNEW_STORE}/saveAllAdminBookNew`;
const GET_DETAIL_ADMINBOOKNEW = `${NS_ADMINBOOKNEW_STORE}/getDetailAdminBookNew`;
const SAVE_DETAIL_ADMINBOOKNEW = `${NS_ADMINBOOKNEW_STORE}/saveDetailAdminBookNew`;
const UPDATE_ADMINBOOKNEW_REQUEST = `${NS_ADMINBOOKNEW_STORE}/updateAdminBookNewRequest`;
const SAVE_UPDATE_ADMINBOOKNEW = `${NS_ADMINBOOKNEW_STORE}/saveUpdateAdminBookNew`;
const CREATE_ADMINBOOKNEW_REQUEST = `${NS_ADMINBOOKNEW_STORE}/createAdminBookNewRequest`;
const DELETE_ADMINBOOKNEW_REQUEST = `${NS_ADMINBOOKNEW_STORE}/deleteAdminBookNewRequest`;

export {
  NS_BOOK_STORE,
  SET_LOADING_STEP,
  NS_ADMINBOOKNEW_STORE,
  GET_ALL_ADMINBOOKNEW,
  SAVE_ALL_ADMINBOOKNEW,
  GET_DETAIL_ADMINBOOKNEW,
  SAVE_DETAIL_ADMINBOOKNEW,
  UPDATE_ADMINBOOKNEW_REQUEST,
  SAVE_UPDATE_ADMINBOOKNEW,
  CREATE_ADMINBOOKNEW_REQUEST,
  DELETE_ADMINBOOKNEW_REQUEST,
};
