const NS_BOOK_STORE = "bookStore";

const NS_ADMINPUBLISHNEW_STORE = "adminpublishnewStore";
const SET_LOADING_STEP = `${NS_BOOK_STORE}/setGlobalLoading`;

const GET_ALL_ADMINPUBLISHNEW = `${NS_ADMINPUBLISHNEW_STORE}/getAllAdminPublishNew`;
const SAVE_ALL_ADMINPUBLISHNEW = `${NS_ADMINPUBLISHNEW_STORE}/saveAllAdminPublishNew`;
const GET_DETAIL_ADMINPUBLISHNEW = `${NS_ADMINPUBLISHNEW_STORE}/getDetailAdminPublishNew`;
const SAVE_DETAIL_ADMINPUBLISHNEW = `${NS_ADMINPUBLISHNEW_STORE}/saveDetailAdminPublishNew`;
const UPDATE_ADMINPUBLISHNEW_REQUEST = `${NS_ADMINPUBLISHNEW_STORE}/updateAdminPublishNewRequest`;
const SAVE_UPDATE_ADMINPUBLISHNEW = `${NS_ADMINPUBLISHNEW_STORE}/saveUpdateAdminPublishNew`;
const CREATE_ADMINPUBLISHNEW_REQUEST = `${NS_ADMINPUBLISHNEW_STORE}/createAdminPublishNewRequest`;
const DELETE_ADMINPUBLISHNEW_REQUEST = `${NS_ADMINPUBLISHNEW_STORE}/deleteAdminPublishNewRequest`;

export {
  NS_BOOK_STORE,
  SET_LOADING_STEP,
  NS_ADMINPUBLISHNEW_STORE,
  GET_ALL_ADMINPUBLISHNEW,
  SAVE_ALL_ADMINPUBLISHNEW,
  GET_DETAIL_ADMINPUBLISHNEW,
  SAVE_DETAIL_ADMINPUBLISHNEW,
  UPDATE_ADMINPUBLISHNEW_REQUEST,
  SAVE_UPDATE_ADMINPUBLISHNEW,
  CREATE_ADMINPUBLISHNEW_REQUEST,
  DELETE_ADMINPUBLISHNEW_REQUEST,
};
